"""
This module is responsible for generating the draft board used to train the drafting agents as well as in the dashboard.
"""

import polars as pl

from nflreadpy import load_ff_rankings
import config

def create_board(preprocess: bool = False) -> pl.DataFrame:
    """
    Creates a full redraft fantasy draft board from data loaded from nflreadpy.

    :param preprocess: Boolean flag to preprocess the draft board further for model training. Defaults to False.

    :returns: Polars DataFrame containing the draft board with optional preprocessing.
    """

    # Load draft rankings from nflreadpy
    board_df = load_ff_rankings(type = 'draft')

    # Check that the board was loaded correctly
    if board_df.is_empty():
        raise Exception("Unable to load draft rankings from nflreadpy")

    # --- Data Cleaning ---
    board_columns = ['id', 'player', 'team', 'bye', 'page_type', 'ecr_type', 'pos',
                    'ecr', 'best', 'worst', 'sd', 'scrape_date']
    board_df = board_df.select(board_columns).sort('ecr')

    # Filter out non-fantasy positions.
    board_df = board_df.filter(pl.col('pos').is_in(config.POSITIONS))

    # Filter for overall redraft rankings.
    board_df = board_df.filter(pl.col('ecr_type') == 'ro').drop('ecr_type')

    # Get rid of the defensive rankings for two-way players (e.g. Travis Hunter)
    # This rarely happens, but it serves as a failsafe.
    board_df = board_df.filter(pl.col('page_type') == 'redraft-overall').drop('page_type')

    # Rename columns for a user-friendly final DataFrame.
    board_df = board_df.rename({
        'id': 'fantasypros_id',
        'player': 'Player',
        'pos': 'Pos',
        'team': 'Team',
        'bye': 'Bye',
        'ecr': 'ECR',
        'best': 'Best',
        'worst': 'Worst',
        'sd': 'Std'
    })

    # Perform training preprocessing if asked
    if preprocess:
        board_df = process_board(board_df)

    return board_df

def process_board(board_df: pl.DataFrame) -> pl.DataFrame:
    """
    Preprocesses the draft board generated by create_board(preprocess=True) for model training.

    Inverts and normalizes the ECR rankings as well as calculates Value over Replacement (VOR) values.

    :param board_df: Polars DataFrame from create_board().

    :return: Processed draft board Polars DataFrame.
    """

    # --- Invert and normalize ECR rankings ---
    max_ecr = board_df['ECR'].max()
    processed_df = board_df.with_columns(
        ((max_ecr - pl.col('ECR')) / max_ecr).round(5).alias('Value')
    )

    # --- Compute Value over Replacement (VOR) ---
    replacement_cutoffs = config.REPLACEMENT_CUTOFFS

    baselines = {}
    for pos, rank in replacement_cutoffs.items():
        # Get the 'Value' of the player at the cutoff rank (0-indexed)
        baselines[pos] = processed_df.filter(pl.col('Pos') == pos)['Value'][rank - 1]

    processed_df = processed_df.with_columns(
        (pl.col('Value') - (pl.col('Pos').replace(baselines).cast(pl.Float64))).round(5).alias('VOR')
    )

    return processed_df

# --- Debug Zone ---
if __name__ == '__main__':
    # Tell polars to show all rows and columns
    pl.Config(tbl_rows=-1, tbl_cols=-1)

    print(create_board(preprocess=True))
